In [1]:
import math
import numpy as np

In [2]:
class Value:
    def __init__(self,data,parents=set(),operation="",label=""):
        self.data=data
        self._prev=parents
        self._op=operation
        self.label=label
        self._backward=lambda :None
        self.grad=0
    def __repr__(self):
        return f"Value({self.data}, {self.label})"
    def __add__(self,other):
        other=other if isinstance(other,Value) else Value(other)
        out=Value(self.data+other.data,(self,other),operation="+")
        def backward():
            self.grad+=out.grad
            other.grad+=out.grad
        out._backward=backward
        return out
    
    def __radd__(self, other):
        return self + other
    def __mul__(self,other):
        other=other if isinstance(other,Value) else Value(other)
        out=Value(self.data*other.data,(self,other),operation="*")
        def backward():
            self.grad+=out.grad*other.data
            other.grad+=out.grad*self.data
        out._backward=backward
        return out
    def __rmul__(self, other):
        return self * other

    def __neg__(self,):
        out=Value(-1*self.data,(self),operation="Negation")
        def backward():
            self.grad+=-1*out.grad
        return out
    def __sub__(self,other):
        other=other if isinstance(other,Value) else Value(other)
        out=Value(self.data-other.data,(self,other),operation="+")
        def backward():
            self.grad+=out.grad
            other.grad-=out.grad
        out._backward=backward
        return out
    def __truediv__(self, other):
        return self * (other**-1)
    def __rtruediv__(self, other):
        return (self**-1) * other
    def __pow__(self,other):
        other=other if isinstance(other,Value) else Value(other)
        out=Value(self.data**other.data,(self,other),operation="exponent")
        def backward():
            self.grad+=other.data*out.grad*(self.data**(other.data-1))
            if self.data > 0:
                other.grad += out.grad * (self.data ** other.data) * math.log(self.data)
        out._backward=backward
        return out
    def tanh(self,):
        t=(math.exp(self.data)-math.exp(-1*self.data))/(math.exp(self.data)+math.exp(-1*self.data))
        out=Value(t,(self),operation="tanh")
        def backward():
            self.grad+=out.grad*(1-t**2)
        out._backward=backward
        return out
    def relu(self,):
        t=self.data if self.data>0 else 0
        out=Value(t,(self),operation="relu")
        def backward():
            if t>0:v=1 
            else:v=0
            self.grad+=out.grad*v
        out._backward=backward
        return out
            


In [3]:
a=Value(2);a.label="a"
b=Value(3);b.label="b"
e=Value(4);e.label="e"

In [4]:
c=a*b;c.label="c"
d=c+e;d.label="d"
f=c*a;f.label="f"
L=f.tanh();L.label="L"
L.grad=1

In [5]:
L._backward()
f._backward()
c._backward()

In [6]:
a.grad,b.grad,e.grad,c.grad,f.grad,L.grad

(1.8120678291211334e-09,
 6.040226097070445e-10,
 0,
 3.0201130485352223e-10,
 1.5100565242676112e-10,
 1)

In [7]:
def backward_pass(Loss):
    topo = []
    visited = set()
    def build_topo(v):
        if v not in visited:
            visited.add(v)
            for child in v._prev:
                build_topo(child)
            topo.append(v)
            
    build_topo(Loss)
    Loss.grad = 1

    for v in reversed(topo):
        v._backward()

In [8]:
x=Value(2);x.label="x"
y=Value(-3);y.label='y'
f=x**2+2*x*y-y**3;f.label="f"

In [9]:
backward_pass(f)

# f=x^2+2xy+y^3
### df/dx=2x+2y
### df/dx=2(x+y)
### at x=2,y=-3
### df/dx=-2

## simmilarly

### df/dy=2x-3y^2
### x=2,y=-3
### df/dy=2*2-3*(-3)^2
### df/dy=4-27
### df/dy=-23

In [10]:
print(f"Forward pass output: {f.data} (Expected: 19.0)")
print(f"x-gradient: {x.grad} (Expected: -2.0)")
print(f"y-gradient: {y.grad} (Expected: -23.0)")

Forward pass output: 19 (Expected: 19.0)
x-gradient: -2 (Expected: -2.0)
y-gradient: -23 (Expected: -23.0)


In [11]:
import numpy as np
class Tensor:
    def __init__(self,data,parents=set(),operation="",label=""):
        self.data = np.atleast_2d(data).astype(float)
        self._prev=parents
        self._op=operation
        self.grad = np.zeros_like(self.data, dtype=float)
        self.label=label
        self._backward=lambda : None
    def __repr__(self):
        return f"Tensor({self.data}), Label={self.label}"
    def __add__(self,other):
        other=other if isinstance(other,Tensor) else Tensor(other)
        out=Tensor(self.data+other.data,(self,other),operation="+")
        def backward():
            self.grad+=out.grad
            other.grad+=out.grad
        out._backward=backward
        return out
    
    def __radd__(self, other):
        return self + other

    def __matmul__(self, other):
        other = other if isinstance(other, Tensor) else Tensor(other)
        out = Tensor(self.data @ other.data, (self, other), operation="@")
    
        def backward():
            self.grad += out.grad @ other.data.T
            other.grad += self.data.T @ out.grad
        
        out._backward = backward
        return out
    def __mul__(self,other):
        other = other if isinstance(other, Tensor) else Tensor(other)
        out = Tensor(self.data * other.data, (self, other), operation="@")
    
        def backward():
            self.grad += out.grad * other.data
            other.grad += self.data * out.grad
        
        out._backward = backward
        return out
    def __sub__(self, other):
        other = other if isinstance(other, Tensor) else Tensor(other)
        out = Tensor(self.data - other.data, (self, other), operation="-")

        def backward():
            self.grad += out.grad
            other.grad -= out.grad

        out._backward = backward
        return out
    def relu(self,):
        out=Tensor(np.maximum(0,self.data),(self,),operation="relu activation")
        def backward():
            self.grad+=out.grad*(self.data>0)
        out._backward=backward
        return out
    def tanh(self,):
        t=np.tanh(self.data)
        out=Tensor(t,(self,),operation="tanh activation")
        def backward():
            self.grad+=out.grad*(1-t**2)
        out._backward=backward
        return out
    
    

In [12]:
# Input matrix 
X = Tensor([[1.0, 2.0]], label="X") 

# Weight matrix 
W = Tensor([[0.5, -0.5], 
            [0.2,  0.8]], label="W")

In [13]:
Z = X @ W
Z.label = "Z"

A = Z.relu()
A.label = "A"
A.grad = np.ones_like(A.data)

In [14]:
A._backward()
Z._backward()

In [15]:
print("Forward Pass Output (A): \n", A.data)
print("Gradient of Weights W: \n", W.grad)
print("Gradient of Inputs X: \n", X.grad)

Forward Pass Output (A): 
 [[0.9 1.1]]
Gradient of Weights W: 
 [[1. 1.]
 [2. 2.]]
Gradient of Inputs X: 
 [[0. 1.]]


In [16]:
def backward(Loss):
    topo = []
    visited = set()
    def build_topo(v):
        if v not in visited:
            visited.add(v)
            for child in v._prev:
                build_topo(child)
            topo.append(v)
            
    build_topo(Loss)
    if isinstance(Loss, Tensor):
        Loss.grad = np.ones_like(Loss.data)
    else:
        Loss.grad = 1
    for v in reversed(topo):
        v._backward()

In [17]:
backward(A)